### PR TITLE
Bug 2065148: set leader election retry times

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
This is a manual cherry-pick of https://github.com/openshift/cluster-nfd-operator/pull/246, can't use bot due the amount of dependencies updated on #246, so I am setting the values by hand.

**Comment by ArangoGutierrez** [comment]
Ready for review  @wabouhamad @lenahorsley

**Review by lenahorsley — COMMENTED** [review]
/lgtm

**Comment by ArangoGutierrez** [comment]
No Tide query for branch release-4.10 found.

**Pull request merged**
