### PR TITLE
Bug 1992739: Name in CSV not matching art.yaml

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Review by lenahorsley — COMMENTED** [review]
/lgtm

**Comment by ArangoGutierrez** [comment]
cherry-pick PR -> https://github.com/openshift/cluster-nfd-operator/pull/198

**Pull request merged**
