### PR TITLE
Bug 1797678:  SecurityContextContstraints endpoint changed, sdk update needed [release 4.3] [testblocker]

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
It is not possible to install the NFD operator, it crashes immediately, endpoint for watching SCC changed from ` /api/v1/securitycontextconstraints ` to `/apis/security.openshift.io/v1/securitycontextconstraints`. 

NFD operator manages a specific SCC for the NFD-master,  `AddToScheme` was not able to register the right type. 
```
{"level":"info","ts":1579886682.20229,"logger":"kubebuilder.controller","msg":"Starting 
EventSource","controller":"nodefeaturediscovery-controller","source":"kind source: /, Kind="} 
{"level":"error","ts":1579886682.202312,"logger":"cmd","msg":"","error":"no kind is registered for the 
type v1.SecurityContextConstraints in scheme \"k8s.io/client-
go/kubernetes/scheme/register.go:60\"","stacktrace":"github.com/openshift/cluster-nfd-
operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/openshift/cluster-
nfd-operator/vendor/github.com/go-
logr/zapr/zapr.go:128\nmain.main\n\t/go/src/github.com/openshift/cluster-nfd-
operator/cmd/manager/main.go:92\nruntime.main\n\t/opt/rh/go-toolset-1.12/root/usr/lib/go-toolset-
1.12-golang/src/runtime/proc.go:200"}
```

Fixes: https://github.com/openshift/cluster-nfd-operator/issues/54

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
@madorn in reference to issue #54

**Comment by sjug** [comment]
We need to find some way to fix the commit situation, pushing 22 more commits to previous branches would be a disaster.

**Comment by zvonkok** [comment]
@ArangoGutierrez we need this also for 4.2 release ^^

**Comment by ArangoGutierrez** [comment]
> @ArangoGutierrez we need this also for 4.2 release ^^
@zvonkok 
https://github.com/openshift/cluster-nfd-operator/pull/77

**Pull request merged**
