### PR TITLE
update crd softLink

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by sjug** [comment]
Do we want to hard code versions in master? Maybe we should have a `latest`?

**Comment by ArangoGutierrez** [comment]
> Do we want to hard code versions in master? Maybe we should have a `latest`?

This is needed by release to get the operator build for the OperatorFramework OLM, that's why is release dependant, trust me I would love to get rid of this soft link. Maybe on this next release when we update to the new Operator SDK this will be better

**Comment by ArangoGutierrez** [comment]
Thanks for the `lgtm` @sjug 

Can we get a second review and `approve` [ @zvonkok , @sjug ]

**Pull request merged**
