### PR TITLE
Fixing the CR name to apply nodes labeling in README.md

### PR DESCRIPTION
**Pull request by ybettan**
Signed-off-by: Yoni Bettan <ybettan@redhat.com>

### CODE REVIEW

**Review by jmencak — APPROVED** [review]
Thank you for the PR, Yoni.
/lgtm
/assign @ArangoGutierrez

**Comment by ybettan** [comment]
YW @jmencak.
Are `ci/prow/ci-index` and `ci/prow/e2e-aws` supposed to fail?

**Comment by jmencak** [comment]
> YW @jmencak. Are `ci/prow/ci-index` and `ci/prow/e2e-aws` supposed to fail?

No, but it is pretty clear this PR is not responsible for the failures.

**Comment by ybettan** [comment]
Do I need to do something for the CI to pass, or just wait? @jmencak

**Review by ArangoGutierrez — APPROVED** [review]

**Comment by jmencak** [comment]
> Do I need to do something for the CI to pass, or just wait? @jmencak

Looking at the job history those failures are pretty consistent, I would not expect retests to help right now until this is fixed elsewhere.  @ArangoGutierrez is more familiar with NFD and will probably know what needs to be changed.

**Comment by ArangoGutierrez** [comment]
We need https://github.com/openshift/cluster-nfd-operator/pull/214 lgtm before this one can go in

**Comment by jmencak** [comment]
> We need #214 lgtm before this one can go in

Sounds like catch 22 unless you want to skip the tests on 214.
/hold
not to waste the CPU cycles by retesting.  Feel free to cancel once this is sorted.

**Pull request merged**
