### PR TITLE
Bug 1883674: Replace operand image

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Replace target for operand image registry

>    zvonkok -> kubernetes_incubator

Upstream operand image can be found at:

    quay.io/kubernetes_incubator/node-feature-discovery

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by zvonkok** [comment]
@ArangoGutierrez We need the downstream node-feature-discovery image here not the upstream. You have setup the mirroring for the operator and the operand. We need here the mirrored operand image.

**Comment by ArangoGutierrez** [comment]
You are totally right, and also to make sense with #81 , will fix that asap

**Comment by ArangoGutierrez** [comment]
@zvonkok PR has been fixed according to your comments, PTAL

**Comment by ArangoGutierrez** [comment]
@zvonkok *PING*

**Comment by ArangoGutierrez** [comment]
* @zvonkok

**Comment by ArangoGutierrez** [comment]
/test e2e-upgrade
*Carlos Eduardo Arango Gutierrez* <https://github.com/ArangoGutierrez>
Software Engineer | R&D Performance & Scale for OpenShift
<https://www.openshift.com/>
Performance & Latency Sensitive Application Platform (PSAP
<https://github.com/openshift-psap>)

He/Him/His - @CarlosEArango <https://twitter.com/CarlosEArango>

@RedHat <https://twitter.com/redhat>   Red Hat
<https://www.linkedin.com/company/red-hat>  Red Hat
<https://www.facebook.com/RedHatInc>

<https://www.redhat.com>

**Comment by ArangoGutierrez** [comment]
> @ArangoGutierrez We need the downstream node-feature-discovery image here not the upstream. You have setup the mirroring for the operator and the operand. We need here the mirrored operand image.


b24d0ec uses downstream image `openshift/origin-node-feature-discovery`

**Pull request merged**
