### PR TITLE
Add description label to Dockerfile

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
@wabouhamad @lenahorsley

**Comment by ArangoGutierrez** [comment]
https://www.theverge.com/2021/11/4/22763535/google-alphabet-drug-discovery-deepmind-ai

**Comment by kpouget** [comment]
I have no cue if this is a flake or not :/

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Pull request merged**
