### PR TITLE
[release-4.2] Bug 1805427: Manual cherry-pick from PR #57 

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
In PR #57 we called for automated cherry-pick via @openshift-cherrypick-robot but it failed 
```
Applying: Added vendor dependencies
Applying: Switching to a supported golang container
Applying: Tuned the Role and addedd AddToScheme before AddToManager
Applying: Make gofmt happy
Applying: Added update vendors dir
Applying: Testing clusterresources and watch
Applying: Testing clusterresources and watch
Applying: Testing clusterresources and watch
Applying: Testing clusterresources and watch
error: Failed to merge in the changes.
Using index info to reconstruct a base tree...
A	manifests/olm-catalog/4.3/nfd.crd.yaml
Falling back to patching base and 3-way merge...
CONFLICT (modify/delete): manifests/olm-catalog/4.3/nfd.crd.yaml deleted in HEAD and modified in Testing clusterresources and watch. Version Testing clusterresources and watch of manifests/olm-catalog/4.3/nfd.crd.yaml left in tree.
Patch failed at 0010 Testing clusterresources and watch
```

This PR is a manual cherry-pick of commits [c15f215, e28a017, 4697032, d2d7c26, 42c7c7e, 02192a3, 3c12999, 95d213e, 4314cb4, 84ddac8, cf9efce, 5f5ec54, 2194231, 3d18edd, 7d34949, 776275a, 194d33a, b4d9f14, 1b38f21, 5c0002e] into branch release-4.2

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
@sdodson why was the cherry-pick label removed? so I can work on it and push it 

thanks :)

**Comment by sdodson** [comment]
> @sdodson why was the cherry-pick label removed? so I can work on it and push it

Was just conferring with @mrunalp given the size of the change.

**Pull request merged**
