### PR TITLE
remove Dockerfile no longer needed

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
this PR can wait until code freeze is lifted

**Review by jmencak — APPROVED** [review]
Thank you for the PR, Ed.  openshift/release is using `Dockerfile`, rather than `Dockerfile.rhel7`, /lgtm
/retest
The only slightly confusing bit is the PR title and the commit log wording.

**Comment by ArangoGutierrez** [comment]
> Thank you for the PR, Ed. openshift/release is using `Dockerfile`, rather than `Dockerfile.rhel7`, /lgtm
> /retest
> The only slightly confusing bit is the PR title and the commit log wording.

looks like your lgtm was not parsed :(

**Comment by ArangoGutierrez** [comment]
@jmencak can I get your help once again here :)

**Comment by jmencak** [comment]
@ArangoGutierrez looks like you don't want to handle the confusing wording :)
/lgtm

**Comment by ArangoGutierrez** [comment]
Removing the file `Dockerfile.rhel7`does NOT affect NFD in any way, shape or form, This PR doesn't need e2e runs 

/override ci/prow/e2e-aws
/override ci/prow/e2e-upgrade

**Pull request merged**
