### PR TITLE
Bug 2051988: Drop namespace from CRD

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
fix for BZ Bug 2019945: openshift-nfd namespace gets stuck in terminating state when trying to delete 
/cc @wabouhamad @lenahorsley

### CODE REVIEW

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Review by lenahorsley — COMMENTED** [review]
/lgtm

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Pull request merged**
