### PR TITLE
[release-4.13] OCPBUGS-10782: Open Move to stable channel + bump to 4.13

### PR DESCRIPTION
**Pull request by locriandev**
Ref. https://issues.redhat.com/browse/ART-5087

### CODE REVIEW

**Comment by thiagoalessio** [comment]
Hi @locriandev, looks like a new rebase is required :(
@yevgeny-shnaidman, apart from the rebase, is there anything else ART needs to do to get this merged?

**Comment by yevgeny-shnaidman** [comment]
/retitle OCPBUGS-10782: Open Move to stable channel + bump to 4.13

**Comment by yevgeny-shnaidman** [comment]
/retitle [release-4.13] OCPBUGS-10782: Open Move to stable channel + bump to 4.13

**Pull request merged**
