### PR TITLE
Bug 1967314: fix logo not present when using OperatorHub

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
Related to https://bugzilla.redhat.com/show_bug.cgi?id=1814822

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Comment by ArangoGutierrez** [comment]
Hey @wabouhamad @lenahorsley I am not sure if this PR is need, I will keep it on-hold and will track the BZ  https://bugzilla.redhat.com/show_bug.cgi?id=1814822 , it seems like NFD is ok, there's something happening at a UI/webbrowser lvl that is not fixable from the operator code.

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Comment by ArangoGutierrez** [comment]
this patch does not affect upgrades, is just a logo check on the CSV 
/override ci/prow/e2e-upgrade

**Pull request merged**
