### PR TITLE
Bug 1898510: This is an manual cherry-pick of #110

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
As discussed in https://github.com/openshift/cluster-nfd-operator/pull/111
@markmc 
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by markmc** [comment]
> As discussed in #111
> @markmc

Patch manager is rotated every week, another patch manager will review this and add cherry-pick-approved label. You still need lgtm, approved, valid-bug, etc.

**Comment by ArangoGutierrez** [comment]
Patchmanager are you there?

**Pull request merged**
