### PR TITLE
Bug 2087511: Fix skipRange

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by bparees** [comment]
lgtm.  not going to /lgtm because the NFD team should make the decision about moving up the minimum upgrade level from 4.6 to 4.9.

**Comment by ArangoGutierrez** [comment]
> lgtm. not going to /lgtm because the NFD team should make the decision about moving up the minimum upgrade level from 4.6 to 4.9.

@wabouhamad @lenahorsley ^^

**Pull request merged**
