### PR TITLE
Update Owners

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
rm Deepthidharwar from psap projects

Deepthidharwar is moving to a diff team inside Red Hat

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by jmencak** [comment]
Thanks for keeping things tidy.
/lgtm

**Comment by ArangoGutierrez** [comment]
Removing someone from OWNERS could not possibly break updates; failures must be orthogonal:

/override ci/prow/e2e-upgrade

**Pull request merged**
