### PR TITLE
Update go mod

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
In this patch:
	- Update dependencies to v0.17.3 tag
	- Update go.mod and go.sum to k8s.io v0.17.3
	- Update pkg/client/client.go to fit new imports requirements

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
Tested on a 3 master / 9 workers OCP 4.4.0 cluster
quay.io test image: quay.io/eduardoarango/cluster-nfd-operator:update_go_mod

```bash
[eduardo@fedora-ws cluster-nfd-operator]$ make deploy
customresourcedefinition.apiextensions.k8s.io/nodefeaturediscoveries.nfd.openshift.io created
sleep 1
for obj in manifests/0100_namespace.yaml manifests/0200_service_account.yaml manifests/0300_cluster_role.yaml manifests/0400_cluster_role_binding.yaml manifests/0600_operator.yaml; do \
	sed 's+REPLACE_IMAGE+quay.io/eduardoarango/cluster-nfd-operator:update_go_mod+g; s+REPLACE_NAMESPACE+openshift-nfd+g; s+IfNotPresent+IfNotPresent+' $obj | kubectl apply -f - ;\
	sleep 1;\
done	
namespace/openshift-nfd created
serviceaccount/nfd-operator created
clusterrole.rbac.authorization.k8s.io/nfd-operator created
clusterrolebinding.rbac.authorization.k8s.io/nfd-operator created
deployment.apps/nfd-operator created
nodefeaturediscovery.nfd.openshift.io/nfd-master-server created
```

**Comment by jmencak** [comment]
From experience I believe you typically want to do a massive update (vendor deps) like this ~1-2 weeks before a feature freeze for a branch.  This will allow you not to have too much churn in the vendor tree and match the k8s deps to exactly the same version OpenShift is using.

**Pull request merged**
