### PR TITLE
Bug 1954881: fix bundle format and CSV

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Operator CSV is not in line with operator-sdk layout leading to failuers
when deploying from operatorHub

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
In sync with https://github.com/openshift/ocp-build-data/pull/911

**Comment by ArangoGutierrez** [comment]
@jupierce would like your review on this PR and parent PR -> openshift/ocp-build-data#911

**Review by wabouhamad — COMMENTED** [review]
/lgtm

**Pull request merged**
