### PR TITLE
Bug 2058256: use library-go for leader elect options

### PR DESCRIPTION
**Pull request by ArangoGutierrez**

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
I will coordinate with Simon before moving forward with this PR
/hold

**Comment by ArangoGutierrez** [comment]
> @ArangoGutierrez: This pull request references [Bugzilla bug 2058256](https://bugzilla.redhat.com/show_bug.cgi?id=2058256), which is invalid:
> 
> * expected the bug to target the "4.11.0" release, but it targets "---" instead
> 
> Comment `/bugzilla refresh` to re-evaluate validity if changes to the Bugzilla bug are made, or edit the title of this pull request to link to a different bug.

@sreber84 if we want a fix into 4.8, we will need to edit the bz to point to 4.11 and then make our way down to 4.8

**Comment by ArangoGutierrez** [comment]
Hey @sreber84 any updates testing this?

**Comment by lenahorsley** [comment]
Tested 15 March 2022
Verified on the4.11.0-0.nightly-2022-03-15-060211 build on an AWS cluster (3 worker and 3 master nodes).

NFD version (from a bundle): quay.io/lenahorsley/nfd-operator-bundle:4.11.202203151049
Kube version: v1.23.3+f017760

Tested performed:
1. Build and deploy NFD bundle. Check the worker node labels.
2. Add a worker node and check new node labels.
3. Remove the newly added node and check the labels on the remaining nodes.
4. Log creation and stability.
5. Check for pods restarts in the openshift-etcd namespace (there were no restarts).

All tests were executed successfully.

**Review by lenahorsley — COMMENTED** [review]
/lgtm

**Pull request merged**
