### PR TITLE
fast-forward release 4.5 to 4.6

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
fast-forward release 4.5 to 4.6

now that  master is being fast forwarded to branch release-4.6 , this PR fast-forward the needed pieces to sync that 

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

### CODE REVIEW

**Comment by zvonkok** [comment]
```
$ gh pr checkout 85
$ grep '4\.5' * -R

manifests/olm-catalog/nfd.package.yaml:- name: '4.5'
manifests/olm-catalog/nfd.package.yaml:  currentCSV: nfd.v4.5.0
```

@ArangoGutierrez ^^ PTAL

**Comment by ArangoGutierrez** [comment]
@zvonkok comment addressed by adc433d

**Comment by ArangoGutierrez** [comment]
@zvonkok we need also the `lgtm` comment

**Pull request merged**
