### PR TITLE
Add skipper configuration

### PR DESCRIPTION
**Pull request by yevgeny-shnaidman**
Allows to execute most of the command in the Makefile
via skipper

[MGMT-11417](https://issues.redhat.com//browse/MGMT-11417)

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
More info on Skipper : https://pkg.go.dev/github.com/zalando/skipper

**Comment by ArangoGutierrez** [comment]
Is this PR mostly for devel purposes? 
Bc remeber the official Dockerfile is built by ART, so you will end up maintaining 2 dockerfiles, devel and prod.
Is this ok?

**Comment by yevgeny-shnaidman** [comment]
skipper is a tool that allows developer to build/configure/etc' the repo without installing anything on their laptop. and quickly switch between different project on the same machine. It does not interfere with the ART flow, since it is a different dockerfile. Maintaining is not an issue, since all we have to keep track of is a GO version

**Comment by yevgeny-shnaidman** [comment]
> Is this PR mostly for devel purposes? Bc remeber the official Dockerfile is built by ART, so you will end up maintaining 2 dockerfiles, devel and prod. Is this ok?

skipper is a tool that allows developer to build/configure/etc' the repo without installing anything on their laptop. and quickly switch between different project on the same machine. It does not interfere with the ART flow, since it is a different dockerfile. Maintaining is not an issue, since all we have to keep track of is a GO version

**Comment by ArangoGutierrez** [comment]
> > Is this PR mostly for devel purposes? Bc remeber the official Dockerfile is built by ART, so you will end up maintaining 2 dockerfiles, devel and prod. Is this ok?
> 
> skipper is a tool that allows developer to build/configure/etc' the repo without installing anything on their laptop. and quickly switch between different project on the same machine. It does not interfere with the ART flow, since it is a different dockerfile. Maintaining is not an issue, since all we have to keep track of is a GO version

be aware that ART tracks the file called Dockerfile, and nothing else to build the final prod image.
/lgtm
/approve

**Pull request merged**
